library(tidyverse)
library(readxl)
library(writexl)
library(scales)
library(flextable)

df <- read_xlsx("df_2025_limpia_4.xlsx")

## nuclear biparental ----

df <- df |> 
  mutate(estructura_familiar = case_match(lista_con_quien_vive,
                                          "Abuela materna" ~ "Extendida ascendente",
                                          "Abuela materna, Tía/s, Primo/s" ~ "Extendida ascendente",
                                          "Abuela materna, Tío/s, Tía/s" ~ "Extendida ascendente",
                                          "Abuela materna, Tío/s, Tía/s, Mascota/s" ~ "Extendida ascendente",
                                          "Abuela materna, Tío/s, Tía/s, Primo/s, Prima/s, Mascota/s" ~ "Extendida ascendente",
                                          "Abuela paterna, Tía/s, Primo/s, Prima/s" ~ "Extendida ascendente",
                                          "Abuela paterna, Tío/s, Mascota/s" ~ "Extendida ascendente",
                                          "Amiga/s o no familiares" ~ "Extendida horizontal afín",
                                          "Amigo/s o no familiares" ~ "Extendida horizontal afín",
                                          "Amigo/s o no familiares, Mascota/s" ~ "Extendida horizontal afín",
                                          "Hermana/s" ~ "Nuclear sin núcleo",
                                          "Hermana/s, Abuela paterna, Tío/s, Mascota/s" ~ "Extendida ascendente",
                                          "Hermana/s, Abuelo materno, Abuela materna, Tía/s, Primo/s, Prima/s, Mascota/s" ~ "Extendida ascendente",
                                          "Hermana/s, Mascota/s, Cuñado/s, Sobrina/s" ~ "Extendida horizontal sanguínea",
                                          "Hermano/s" ~ "Nuclear sin núcleo",
                                          "Hermano/s, Abuela materna, Tía/s, Primo/s, Prima/s" ~ "Extendida ascendente",
                                          "Hermano/s, Abuelo paterno, Tía/s" ~ "Extendida ascendente",
                                          "Hermano/s, Hermana/s" ~ "Nuclear sin núcleo",
                                          "Hermano/s, Hermana/s, Abuela materna" ~ "Extendida ascendente",
                                          "Hermano/s, Hermana/s, Abuelo materno, Abuela materna" ~ "Extendida ascendente",
                                          "Hermano/s, Mascota/s, Sobrino/s" ~ "Extendida horizontal sanguínea",
                                          "Hija/s" ~ "Nuclear descendente monoparental",
                                          "Hijo/s, Hija/s" ~ "Nuclear descendente monoparental",
                                          "Hijo/s, Hija/s, Mascota/s" ~ "Nuclear descendente monoparental",
                                          "Mamá" ~ "Nuclear monoparental materna",
                                          "Mamá, Abuela materna" ~ "Extendida ascendente",
                                          "Mamá, Abuela materna, Mascota/s" ~ "Extendida ascendente",
                                          "Mamá, Abuela materna, Primo/s" ~ "Extendida ascendente",
                                          "Mamá, Abuela materna, Tía/s" ~ "Extendida ascendente",
                                          "Mamá, Abuela materna, Tía/s, Prima/s, Mascota/s" ~ "Extendida ascendente",
                                          "Mamá, Abuela materna, Tío/s, Mascota/s" ~ "Extendida ascendente",
                                          "Mamá, Abuela materna, Tío/s, Pareja" ~ "Extendida ascendente",
                                          "Mamá, Abuela materna, Tío/s, Tía/s, Primo/s, Prima/s, Mascota/s" ~ "Extendida ascendente",
                                          "Mamá, Abuelo materno, Abuela materna" ~ "Extendida ascendente",
                                          "Mamá, Abuelo materno, Abuela materna, Mascota/s" ~ "Extendida ascendente",
                                          "Mamá, Abuelo materno, Abuela materna, Tío/s, Tía/s, Primo/s" ~ "Extendida ascendente",
                                          "Mamá, Abuelo paterno" ~ "Extendida ascendente",
                                          "Mamá, Amiga/s o no familiares, Mascota/s" ~ "Nuclear monoparental materna",
                                          "Mamá, Hermana/s" ~ "Nuclear monoparental materna",
                                          "Mamá, Hermana/s, Abuela materna" ~ "Extendida ascendente",
                                          "Mamá, Hermana/s, Abuela materna, Mascota/s" ~ "Extendida ascendente",
                                          "Mamá, Hermana/s, Abuelo materno, Abuela materna, Primo/s, Mascota/s" ~ "Extendida ascendente",
                                          "Mamá, Hermana/s, Abuelo materno, Abuela materna, Tía/s, Prima/s" ~ "Extendida ascendente",
                                          "Mamá, Hermana/s, Abuelo materno, Tía/s, Prima/s, Mascota/s" ~ "Extendida ascendente",
                                          "Mamá, Hermana/s, Mascota/s" ~ "Nuclear monoparental materna",
                                          "Mamá, Hermana/s, Mascota/s, Sobrino/s" ~ "Extendida horizontal sanguínea",
                                          "Mamá, Hermana/s, Pareja, Hija/s" ~ "Extendida descendente",
                                          "Mamá, Hermana/s, Pareja, Hijo/s" ~ "Extendida descendente",
                                          "Mamá, Hermana/s, Prima/s" ~ "Extendida horizontal sanguínea",
                                          "Mamá, Hermana/s, Tío/s, Tía/s, Primo/s, Mascota/s" ~ "Extendida horizontal sanguínea",
                                          "Mamá, Hermano/s" ~ "Nuclear monoparental materna",
                                          "Mamá, Hermano/s, Abuela materna" ~ "Extendida ascendente",
                                          "Mamá, Hermano/s, Abuela materna, Mascota/s" ~ "Extendida ascendente",
                                          "Mamá, Hermano/s, Abuela materna, Primo/s, Mascota/s" ~ "Extendida ascendente",
                                          "Mamá, Hermano/s, Abuela materna, Tía/s, Mascota/s" ~ "Extendida ascendente",
                                          "Mamá, Hermano/s, Abuela materna, Tío/s, Mascota/s" ~ "Extendida ascendente",
                                          "Mamá, Hermano/s, Abuela materna, Tío/s, Tía/s, Mascota/s" ~ "Extendida ascendente",
                                          "Mamá, Hermano/s, Abuelo materno" ~ "Extendida ascendente",
                                          "Mamá, Hermano/s, Abuelo materno, Abuela materna" ~ "Extendida ascendente",
                                          "Mamá, Hermano/s, Abuelo materno, Abuela materna, Tía/s, Prima/s" ~ "Extendida ascendente",
                                          "Mamá, Hermano/s, Hermana/s" ~ "Nuclear monoparental materna",
                                          "Mamá, Hermano/s, Hermana/s, Abuela materna" ~ "Extendida ascendente",
                                          "Mamá, Hermano/s, Hermana/s, Abuela materna, Abuela paterna, Mascota/s" ~ "Extendida ascendente",
                                          "Mamá, Hermano/s, Hermana/s, Abuela materna, Mascota/s, Sobrino/s" ~ "Extendida ascendente",
                                          "Mamá, Hermano/s, Hermana/s, Abuela materna, Tío/s, Tía/s, Prima/s" ~ "Extendida ascendente",
                                          "Mamá, Hermano/s, Hermana/s, Abuelo materno, Abuela materna, Tía/s, Primo/s, Mascota/s" ~ "Extendida ascendente",
                                          "Mamá, Hermano/s, Hermana/s, Mascota/s" ~ "Nuclear monoparental materna",
                                          "Mamá, Hermano/s, Hija/s" ~ "Extendida descendente",
                                          "Mamá, Hermano/s, Hijo/s, Hija/s" ~ "Extendida descendente",
                                          "Mamá, Hermano/s, Mascota/s" ~ "Nuclear monoparental materna",
                                          "Mamá, Hermano/s, Pareja, Hijo/s" ~ "Extendida descendente",
                                          "Mamá, Hermano/s, Prima/s" ~ "Extendida descendente",
                                          "Mamá, Hermano/s, Sobrina/s" ~ "Extendida horizontal sanguínea",
                                          "Mamá, Hermano/s, Sobrino/s" ~ "Extendida horizontal sanguínea",
                                          "Mamá, Hermano/s, Tío/s, Pareja, Mascota/s" ~ "Extendida horizontal sanguínea",
                                          "Mamá, Hijo/s, Hija/s" ~ "Extendida descendente",
                                          "Mamá, Mascota/s" ~ "Nuclear monoparental materna",
                                          "Mamá, Pareja de mi mamá" ~ "Nuclear biparental",
                                          "Mamá, Pareja de mi mamá, Abuela materna, Tío/s, Tía/s, Mascota/s" ~ "Extendida ascendente",
                                          "Mamá, Pareja de mi mamá, Hermana/s" ~ "Nuclear biparental",
                                          "Mamá, Pareja de mi mamá, Hermana/s, Abuela materna, Primo/s, Prima/s, Mascota/s" ~ "Extendida ascendente",
                                          "Mamá, Pareja de mi mamá, Hermana/s, Amigo/s o no familiares, Mascota/s" ~ "Extendida horizontal afín",
                                          "Mamá, Pareja de mi mamá, Hermano/s" ~ "Nuclear biparental",
                                          "Mamá, Pareja de mi mamá, Hermano/s, Abuela materna, Tío/s, Tía/s, Primo/s" ~ "Extendida ascendente",
                                          "Mamá, Pareja de mi mamá, Hermano/s, Hermana/s, Mascota/s" ~ "Nuclear biparental",
                                          "Mamá, Pareja de mi mamá, Hermano/s, Hermana/s, Tía/s, Mascota/s" ~ "Extendida horizontal sanguínea",
                                          "Mamá, Pareja de mi mamá, Hermano/s, Mascota/s" ~ "Nuclear biparental",
                                          "Mamá, Pareja de mi mamá, Hermano/s, Primo/s" ~ "Extendida horizontal sanguínea",
                                          "Mamá, Pareja de mi mamá, Mascota/s" ~ "Nuclear biparental",
                                          "Mamá, Prima/s, Mascota/s" ~ "Extendida horizontal sanguínea",
                                          "Mamá, Tía/s, Hija/s, Mascota/s" ~ "Extendida descendente",
                                          "Mamá, Tía/s, Mascota/s" ~ "Extendida horizontal sanguínea",
                                          "Mamá, Tía/s, Prima/s, Hijo/s, Esposo de mi prima y sus hijos" ~ "Extendida descendente",
                                          "Mamá, Tío/s" ~ "Extendida horizontal sanguínea",
                                          "Mamá, Tío/s, Tía/s, Prima/s, Mascota/s" ~ "Extendida horizontal sanguínea",
                                          "Mascota/s, Solo/a" ~ "Unipersonal",
                                          "Papá" ~ "Nuclear monoparental paterna",
                                          "Papá, Hermana/s" ~ "Nuclear monoparental paterna",
                                          "Papá, Hermana/s, Tío/s, Tía/s, Prima/s, Mascota/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Hermano/s" ~ "Nuclear monoparental paterna",
                                          "Papá, Hermano/s, Abuela paterna" ~ "Extendida ascendente",
                                          "Papá, Hermano/s, Hermana/s" ~ "Nuclear monoparental paterna",
                                          "Papá, Hermano/s, Hermana/s, Abuela materna" ~ "Extendida ascendente",
                                          "Papá, Hermano/s, Hermana/s, Abuelo paterno, Abuela paterna, Tío/s, Primo/s, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Hermano/s, Hermana/s, Tía/s, Primo/s, Prima/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Hermano/s, Hermana/s, Tío/s, Mascota/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Hermano/s, Hermana/s, Tío/s, Primo/s, Cuñado/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Hermano/s, Mascota/s" ~ "Nuclear monoparental paterna",
                                          "Papá, Mamá" ~ "Nuclear biparental",
                                          "Papá, Mamá, Abuela materna, Tío/s, Tía/s, Primo/s, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Abuelo materno" ~ "Extendida ascendente",
                                          "Papá, Mamá, Abuelo materno, Abuela materna" ~ "Extendida ascendente",
                                          "Papá, Mamá, Abuelo materno, Tía/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Abuelo paterno" ~ "Extendida ascendente",
                                          "Papá, Mamá, Abuelo paterno, Abuela paterna, Tía/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermana/s" ~ "Nuclear biparental",
                                          "Papá, Mamá, Hermana/s, Abuela materna" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermana/s, Abuela materna, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermana/s, Abuela paterna" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermana/s, Abuela paterna, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermana/s, Abuela paterna, Tío/s, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermana/s, Abuela paterna, Tío/s, Tía/s, Primo/s, Prima/s, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermana/s, Abuelo materno" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermana/s, Abuelo materno, Abuela materna" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermana/s, Abuelo materno, Abuela materna, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermana/s, Abuelo materno, Abuela materna, Tía/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermana/s, Abuelo materno, Abuela materna, Tía/s, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermana/s, Abuelo materno, Abuela materna, Tío/s, Tía/s, Primo/s, Prima/s, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermana/s, Abuelo materno, Abuela paterna, Tío/s, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermana/s, Abuelo materno, Sobrina/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermana/s, Hija/s, Mascota/s" ~ "Extendida descendente",
                                          "Papá, Mamá, Hermana/s, Mascota/s" ~ "Nuclear biparental",
                                          "Papá, Mamá, Hermana/s, Mascota/s, Cuñado/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Mamá, Hermana/s, Mascota/s, Sobrino/s, Cuñada/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Mamá, Hermana/s, Pareja, Mascota/s" ~ "Extendida descendente sin hijos",
                                          "Papá, Mamá, Hermana/s, Prima/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Mamá, Hermana/s, Primo/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Mamá, Hermana/s, Tío/s, Mascota/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Mamá, Hermana/s, Tío/s, Tía/s, Primo/s, Mascota/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Mamá, Hermana/s, Tío/s, Tía/s, Primo/s, Prima/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Mamá, Hermano/s" ~ "Nuclear biparental",
                                          "Papá, Mamá, Hermano/s, Abuela materna" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermano/s, Abuela materna, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermano/s, Abuela paterna, Hija/s, Sobrina/s" ~ "Extendida descendente",
                                          "Papá, Mamá, Hermano/s, Abuela paterna, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermano/s, Abuela paterna, Tío/s, Tía/s, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermano/s, Abuelo materno, Abuela materna, Tío/s, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermano/s, Abuelo materno, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermano/s, Abuelo materno, Tía/s, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermano/s, Abuelo paterno, Abuela paterna, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermano/s, Abuelo paterno, Abuela paterna, Tío/s, Tía/s, Primo/s, Prima/s, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermano/s, Amigo/s o no familiares" ~ "Nuclear biparental",
                                          "Papá, Mamá, Hermano/s, Cuñada/s, Sobrino/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Mamá, Hermano/s, Hermana/s" ~ "Nuclear biparental",
                                          "Papá, Mamá, Hermano/s, Hermana/s, Abuela materna" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermano/s, Hermana/s, Abuela materna, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermano/s, Hermana/s, Abuela materna, Primo/s, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermano/s, Hermana/s, Abuela materna, Tía/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermano/s, Hermana/s, Abuela materna, Tío/s, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermano/s, Hermana/s, Abuela paterna, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermano/s, Hermana/s, Abuelo materno, Abuela materna" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermano/s, Hermana/s, Abuelo materno, Abuela materna, Tío/s, Tía/s, Primo/s, Prima/s, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermano/s, Hermana/s, Abuelo materno, Tío/s, Primo/s, Prima/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermano/s, Hermana/s, Abuelo paterno, Abuela paterna" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermano/s, Hermana/s, Abuelo paterno, Abuela paterna, Tía/s, Primo/s, Prima/s, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermano/s, Hermana/s, Abuelo paterno, Mascota/s" ~ "Extendida ascendente",
                                          "Papá, Mamá, Hermano/s, Hermana/s, Hija/s" ~ "Extendida descendente",
                                          "Papá, Mamá, Hermano/s, Hermana/s, Mascota/s" ~ "Nuclear biparental",
                                          "Papá, Mamá, Hermano/s, Hermana/s, Mascota/s, Cuñada/s, Sobrina/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Mamá, Hermano/s, Hermana/s, Primo/s, Mascota/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Mamá, Hermano/s, Hermana/s, Tía/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Mamá, Hermano/s, Hijo/s" ~ "Extendida descendente",
                                          "Papá, Mamá, Hermano/s, Mascota/s" ~ "Nuclear biparental",
                                          "Papá, Mamá, Hermano/s, Mascota/s, Cuñada/s, Sobrino/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Mamá, Hermano/s, Pareja, Hija/s, Mascota/s" ~ "Extendida descendente",
                                          "Papá, Mamá, Hermano/s, Prima/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Mamá, Hermano/s, Primo/s, Mascota/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Mamá, Hermano/s, Tía/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Mamá, Hermano/s, Tía/s, Mascota/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Mamá, Hermano/s, Tía/s, Primo/s, Prima/s, Mascota/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Mamá, Hermano/s, Tío/s, Mascota/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Mamá, Hermano/s, Tío/s, Primo/s, Mascota/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Mamá, Hermano/s, Tío/s, Tía/s, Mascota/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Mamá, Hermano/s, Tío/s, Tía/s, Primo/s, Prima/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Mamá, Hijo/s" ~ "Extendida descendente",
                                          "Papá, Mamá, Hijo/s, Mascota/s" ~ "Extendida descendente",
                                          "Papá, Mamá, Mascota/s" ~ "Nuclear biparental",
                                          "Papá, Mamá, Tía/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Mamá, Tía/s, Mascota/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Mamá, Tío/s, Tía/s, Primo/s, Prima/s" ~ "Extendida horizontal sanguínea",
                                          "Papá, Pareja de mi papá, Hermana/s" ~ "Nuclear biparental",
                                          "Papá, Pareja de mi papá, Hermano/s, Hermana/s, Pareja" ~ "Extendida descendente sin hijos",
                                          "Papá, Tío/s, Tía/s, Primo/s, Prima/s" ~ "Extendida horizontal sanguínea",
                                          "Pareja" ~ "Nuclear descendente sin hijo/a/s",
                                          "Pareja de mi papá, Mamá, Hermana/s, Mascota/s" ~ "Nuclear biparental",
                                          "Pareja de mi papá, Mamá, Hermano/s, Abuela materna" ~ "Extendida ascendente",
                                          "Pareja, Hija/s" ~ "Nuclear descendente biparental",
                                          "Pareja, Hijastra, Suegros" ~ "Extendida descendente",
                                          "Pareja, Hijo/s" ~ "Nuclear descendente biparental",
                                          "Pareja, Hijo/s, Hija/s" ~ "Nuclear descendente biparental",
                                          "Pareja, Hijo/s, Hija/s, Mascota/s" ~ "Nuclear descendente biparental",
                                          "Pareja, Hijo/s, Mascota/s" ~ "Nuclear descendente biparental",
                                          "Pareja, Mascota/s" ~ "Nuclear descendente sin hijo/a/s",
                                          "Pareja, Suegra" ~ "Extendida descendente sin hijos",
                                          "Solo/a" ~ "Unipersonal",
                                          "Tía/s, Hijo/s" ~ "Extendida descendente",
                                          "Tía/s, Prima/s" ~ "Extendida horizontal sanguínea")) |> 
  relocate(estructura_familiar, .after = lista_con_quien_vive)

write_xlsx(df, "df_2025_limpia_para_analisis.xlsx")


#lista_familiares <- as.data.frame(table(df$lista_con_quien_vive))
#write_xlsx(lista_familiares, "lista_familiares.xlsx")

